### ISSUE TITLE
Spiders

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/sandcrawler#101]
Ping @boogheta, seriously? Wouldn't this be better than scraper since the scraper is kinda the script injected itself?

**Comment by boogheta** [comment]
I would go for crawler initially.
Although, since artoo will be at the core of those instances, I would now rather be in favor of something a lot more significant: let's call these "droids"!

**Comment by jacomyal** [comment]
Though, "spider" is kind of a relevant name here, isn't it?

**Comment by boogheta** [comment]
Well, if you consider scrapy to be the reference (which is surprising for such a js aficionado), maybe. But since it merely is a metaphor of the arachnid crawling though the web, I guess the other metaphor of droids accompanying you on your tie-fighter when battling against the evil empire of anti-scraping is also very relevant.

**Comment by paulgirard** [comment]
What a spider would do in a sandcrawler ?
I would vote for Jawa.
Droid is fair enough.

**Comment by jacomyal** [comment]
@boogheta It actually appears that Scrappy (which I am not familiar with at all) is actually not the only reference. I summon Wikipedia as the main witness! http://en.wikipedia.org/wiki/Web_spider

@paulgirard Also, I am pretty sure there actually are spiders in sandcrawlers. Authors probably just forgot to mention them, I guess...

**Comment by jacomyal** [comment]
Also http://starwars.wikia.com/wiki/Spider

**Comment by Yomguithereal** [comment]
[Behold](http://starwars.wikia.com/wiki/Spider).
